### ISSUE TITLE
8. Добавление Редакса

### ISSUE THREAD

**Issue by ilyasidorchik** [ilyasidorchik/sdamgia-introtask-ruslan#11]
Даше понравился наш поиск, но она почему-то хочет видеть ответ сразу в нескольких местах: под формой поиска и в шапке страницы. В шапке достаточно отобразить название найденного предмета, например «Русский язык».

---
Данные нужны в нескольких местах нашего приложения. Значит, прокидывать стейт не вариант. Нужен глобальный стейт, хранилище состояния — Редакс. Давай запланируем встречу, где сделаем задание вместе, а пока попробуй поразбираться сам.

**Comment by akseonowww** [comment]
>  Давай запланируем встречу

Я скорее в субботу смогу.

**Comment by ilyasidorchik** [comment]
Я сделал пул-реквест с тем, что [сегодня написал](https://github.com/ilyasidorchik/sdamgia-introtask-ruslan/pull/12). Твоя задача —
1. отвести от мастера новую ветку, повторить, что я сделал;
2. добавить футер, который тоже получает данные из стора;
3. обработать ошибки при работе с АПИ.
