### ISSUE TITLE
9. Кнопка на Тайпскрипте для библиотеки компонентов

### ISSUE THREAD

**Issue by ilyasidorchik** [ilyasidorchik/sdamgia-introtask-ruslan#14]
Наша пользователь Даша узнала о новом продукте «Сдам ГИА», который сделал другой разработчик. Даше не нравится, что в том продукте кнопки выглядят по-другому. Давай поможем Даше: напишем компонент кнопки, который возьмут другие разработчики.

---

Предполагается, что кнопку будут использовать многие программисты. Чтобы им было понятнее, нужно описать типы пропсов компонента: `className` и `disabled` в нашем случае. Для этого подходит надстройка над Яваскриптом — Тайпскрипт.

Ты добавляешь Тайпскрипт в проект, создаёшь компонент `Button.tsx` и пишешь интерфейс с описанием пропсов. Как только это проверено наставником, можно перенести стили кнопки в `Button.scss`.
<br />
Документация CRA (Create React App). [Как добавить Тайпскрипт](https://create-react-app.dev/docs/adding-typescript/)

**Comment by akseonowww** [comment]
Может ещё в пропс кидать название кнопки?

**Comment by ilyasidorchik** [comment]
> Может ещё в пропс кидать название кнопки?

А зачем он нужен? У нас же обработка формы на стороне клиента.

**Comment by akseonowww** [comment]
А расширение оставить *.TSX? 
Ты же в прошлый раз посоветовал JS писать без X на конце (*.JSX --> *.JS). Хотя JS же работает в браузере, TypeScript нет, значит можно оставить. Не знаю, блин.

**Comment by ilyasidorchik** [comment]
> А расширение оставить .tsx?

Да.

Дело в том, что если в файле `.tsx` написать JSX, то ничего не получится. Поэтому пока пишем `.tsx`.

В функциях-хелперах или других местах, где нет JSX, пишем `.ts`.

**Comment by akseonowww** [comment]
> > А расширение оставить .tsx?
> 
> Да.
> 
> Дело в том, что если в файле `.tsx` написать JSX, то ничего не получится. Поэтому пока пишем `.tsx`.
> 
> В функциях-хелперах или других местах, где нет JSX, пишем `.ts`.

А как понять что нет JSX?

**Comment by ilyasidorchik** [comment]
> А как понять что нет JSX?

Простой ответ: нет хтмл-тегов.

См. также:
Документация Реакта. [JSX](https://ru.reactjs.org/docs/introducing-jsx.html)
